/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DerpRouteImport } from './routes/derp'
import { Route as IndexRouteImport } from './routes/index'

const DerpRoute = DerpRouteImport.update({
  id: '/derp',
  path: '/derp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/derp': typeof DerpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/derp': typeof DerpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/derp': typeof DerpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/derp'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/derp'
  id: '__root__' | '/' | '/derp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DerpRoute: typeof DerpRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/derp': {
      id: '/derp'
      path: '/derp'
      fullPath: '/derp'
      preLoaderRoute: typeof DerpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DerpRoute: DerpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
